### ISSUE TITLE
How to compile a release build?

### ISSUE THREAD

**Issue by Alex313031** [christoh/fdformat#3]
I'm not used to pascal on dos. What would I need to compile it?
Some quick researching brings up NASM, Wacom Linker, and Open Pascal or Turbo Pascal SDKs.

**Comment by christoh** [comment]
You will need ancient tools to compile this. Try Turbo Pascal 5.0 and Microsoft MASM on MS-DOS. It will not compile with recent tools. If you just want a running version, check out the source-and-binaries branch

**Comment by Alex313031** [comment]
@christoh I was able to build it!

However, it took me a while to figure out and track down all the needed build stuff. I propose we add a ZIP with all the needed stuff. What I needed was

Turbo Pascal 6.0
Turbo Assembler 5.0
LZEXE 0.91
PKUNZIP 2.0
It says I also need 4DOS as my comspec, but I found everything worked fine on MS-DOS 6.22 with standard command.com. This makes sense, as this source was released in 1991 with MS-DOS 5.0, and 6.22's command.com accepts alot more wildcards. In particular the *$G that is in the makefile wouldn't have worked with dos 5.0.

Can I make a PR with the .zip?? All these programs are now in the public domain and downloadable from many sites, including WinWorldPC (I'm sure you've heard of it).

**Comment by Alex313031** [comment]
@christoh 
https://github.com/Alex313031/fdformat-ng/

**Comment by christoh** [comment]
Yes, I will accept a PR but please prepare it for the "source and binaries" branch

**Comment by Alex313031** [comment]
@christoh Noice! Ok sir.

I compiled fdformat.exe for 286 instead of 8088. Maybe it's the placebo effect, but I swear it's faster on my PS/2 55SX with 16Mhz. 386SX.

**Comment by Alex313031** [comment]
@christoh Here is the PR > https://github.com/christoh/fdformat/pull/5

**Comment by christoh** [comment]
Merged it. Thank you

**Comment by christoh** [comment]
Merged it. Thank you
